### PR TITLE
Moved requirements.txt contents into setup.py, fix dev_appserver spinning.

### PR DESCRIPTION
**Pull request by mindhog**
@aschults @JustinBeckwith pls review.

Specify requirements.txt in install_requires so that the instructions actually
do installation of the dependencies.

Change-Id: I3e3d8683a42345667654f0a64925f3dac6900499

### CODE REVIEW

**Comment by aschults** [comment]
CI failed. Is an empty requirements.txt necessary or are there some settings to fix this?

**Comment by zeapo** [comment]
@aschults it fails probably cause of https://github.com/GoogleCloudPlatform/appstart/blob/master/.travis.yml#L9

**Comment by mindhog** [comment]
Looking into this right now.

**Comment by mindhog** [comment]
@aschults PTAL?

**Comment by aschults** [comment]
LGTM

**Pull request merged**
